services:
  nginx:
    image: nginx:1.27.0
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/
    user: "1000:1000"

  mysql:
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf_db
      MYSQL_USER: sf_user
      MYSQL_PASSWORD: sf_pass
    command:
      mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=sf_user
      - PMA_PASSWORD=sf_pass
    depends_on:
      - mysql
    ports:
      - "8080:80"
